//! WS63 timer and software-interrupt scheduler port.
//!
//! This module owns the chip mechanism needed by [`crate::start_with_port`].
//! Applications provide caller-owned [`crate::SchedulerStorage`], bind the two
//! interrupt symbols, and pass the singleton TIMER and SYS_CTL1 tokens to
//! [`start`]. A successful start transfers all three resources permanently to
//! the process-wide scheduler.

use core::marker::PhantomData;
use core::num::{NonZeroU32, NonZeroUsize};

use hisi_hal::interrupt;
use hisi_hal::peripherals::{SysCtl1, Timer};
use hisi_hal::software_interrupt::SoftwareInterrupt0;
use hisi_hal::time::Instant;
use hisi_hal::timer::TimerAlarm0;

use crate::{
    InstalledSchedulerStorage, Ported, PortedConfig, RunPolicy, RuntimeHandle, RuntimeResources,
    SchedulerPort, StartError,
};

/// TIMER_INT0 interrupt handler implemented by the WS63 scheduler port.
pub enum TimerInterrupt {}

/// SOFT_INT0 interrupt handler implemented by the WS63 scheduler port.
pub enum SoftwareInterrupt {}

/// Type-level proof that an interrupt symbol is bound to `Handler`.
///
/// # Safety
///
/// An implementation must export exactly one target interrupt symbol for the
/// requested handler and call that handler without running user code first.
pub unsafe trait Binding<Handler> {}

/// WS63 scheduler configuration.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Config {
    /// Minimum stack allocation applied to each dynamically created task.
    pub minimum_stack_size: NonZeroUsize,
    /// Default policy for vendor/runtime tasks.
    pub radio_task_policy: RunPolicy,
    /// Maximum continuous scheduler-lock hold time.
    pub max_scheduler_lock_duration: NonZeroU32,
}

impl Default for Config {
    fn default() -> Self {
        let config = PortedConfig::default();
        Self {
            minimum_stack_size: config.minimum_stack_size,
            radio_task_policy: config.radio_task_policy,
            max_scheduler_lock_duration: config.max_scheduler_lock_duration,
        }
    }
}

impl From<Config> for PortedConfig {
    fn from(config: Config) -> Self {
        Self {
            minimum_stack_size: config.minimum_stack_size,
            radio_task_policy: config.radio_task_policy,
            max_scheduler_lock_duration: config.max_scheduler_lock_duration,
        }
    }
}

/// WS63 peripheral and caller-owned storage resources consumed by [`start`].
pub struct Resources<'d, Irqs, const N: usize> {
    /// TIMER singleton used as the scheduler's one-shot alarm.
    pub timer: Timer<'d>,
    /// SYS_CTL1 singleton used for deferred rescheduling through SOFT_INT0.
    pub software_interrupt: SysCtl1<'d>,
    /// Installed caller-owned task-stack storage for `N` dynamic tasks.
    pub storage: InstalledSchedulerStorage<N>,
    /// Fail-stop handler for scheduler contract violations.
    pub contract_violation: fn(crate::ContractViolation) -> !,
    /// Type-level proof generated by [`crate::bind_interrupts`].
    pub irqs: Irqs,
}

/// Typed capability for the process-wide WS63 scheduler.
///
/// Dropping this value does not stop the scheduler. A successful [`start`]
/// permanently transfers TIMER and SYS_CTL1 to the process-wide runtime.
#[must_use = "retain the WS63 runtime to access its typed ported capabilities"]
pub struct Runtime<'d> {
    handle: RuntimeHandle<Ported>,
    _peripherals: PhantomData<&'d mut ()>,
}

impl Runtime<'_> {
    /// Access the typed ported-runtime capability.
    pub const fn handle(&self) -> &RuntimeHandle<Ported> {
        &self.handle
    }
}

/// Starts the scheduler through the native WS63 timer/software-interrupt port.
///
/// The interrupt binding is checked through `Irqs`; both peripheral tokens are
/// transferred permanently to the process-wide runtime. Global interrupts are
/// enabled only after the scheduler and its RF runtime contract have been
/// installed.
pub fn start<'d, Irqs, const N: usize>(
    config: Config,
    resources: Resources<'d, Irqs, N>,
) -> Result<Runtime<'d>, StartError>
where
    Irqs: Binding<TimerInterrupt> + Binding<SoftwareInterrupt>,
{
    let Resources {
        timer,
        software_interrupt,
        storage,
        contract_violation,
        irqs: _,
    } = resources;
    let timer = TimerAlarm0::new(timer);
    let software_interrupt = SoftwareInterrupt0::new(software_interrupt);
    let handle = crate::start_with_port_and_storage(
        config.into(),
        RuntimeResources { monotonic_ms },
        storage,
        SchedulerPort {
            max_timer_delay: NonZeroU32::new(TimerAlarm0::MAX_DELAY_MS)
                .expect("WS63 TIMER0 maximum delay is non-zero"),
            arm_timer: TimerAlarm0::arm_millis,
            disarm_timer: TimerAlarm0::disarm,
            pend_reschedule: SoftwareInterrupt0::pend_interrupt,
            contract_violation,
        },
    )?;

    // TIMER and SYS_CTL1 back process-wide function-pointer callbacks installed
    // above. They cannot be reclaimed without stopping the scheduler, which is
    // intentionally unsupported.
    core::mem::forget(timer);
    core::mem::forget(software_interrupt);

    // SAFETY: both interrupt sources have live owning tokens, their symbols are
    // proven by `Irqs`, and the scheduler state is fully installed.
    unsafe { interrupt::enable_global() };
    crate::request_reschedule();

    Ok(Runtime {
        handle,
        _peripherals: PhantomData,
    })
}

fn monotonic_ms() -> u64 {
    // WS63's boot TCXO counter runs at 24 MHz.
    Instant::now().raw() / 24_000
}

#[doc(hidden)]
pub unsafe fn handle_timer_interrupt() {
    TimerAlarm0::clear_interrupt();
    crate::interrupt_enter();
    crate::on_timer_interrupt();
    crate::interrupt_exit();
}

#[doc(hidden)]
pub unsafe fn handle_software_interrupt() {
    SoftwareInterrupt0::clear_interrupt();
    crate::interrupt_enter();
    crate::on_software_interrupt();
    crate::interrupt_exit();
}

/// Binds the WS63 scheduler's timer and deferred-reschedule interrupt symbols.
#[macro_export]
macro_rules! bind_interrupts {
    (
        struct $name:ident {
            TIMER_INT0 => $timer:ty;
            SOFT_INT0 => $software:ty;
        }
    ) => {
        pub struct $name {
            _private: core::marker::PhantomData<()>,
        }

        impl $name {
            pub const fn new() -> Self {
                Self {
                    _private: core::marker::PhantomData,
                }
            }
        }

        unsafe impl $crate::ws63::Binding<$timer> for $name {}
        unsafe impl $crate::ws63::Binding<$software> for $name {}

        #[unsafe(no_mangle)]
        extern "C" fn TIMER_INT0() {
            // SAFETY: this function is entered only from the WS63 interrupt
            // vector bound above.
            unsafe { $crate::ws63::handle_timer_interrupt() }
        }

        #[unsafe(no_mangle)]
        extern "C" fn SOFT_INT0() {
            // SAFETY: this function is entered only from the WS63 interrupt
            // vector bound above.
            unsafe { $crate::ws63::handle_software_interrupt() }
        }
    };
}
